FractalTracer: Amazingbox.h AnalyticDEObject.h BenesiPine2.h Cubicbulb.h Dual.h DualDEObject.h main.cpp Mandelbulb.h MengerSponge.h Material.h Octopus.h RiemannSphere.h QuadraticJuliabulb.h Ray.h real.h Renderer.h Scene.h SceneObject.h SimpleObjects.h stb_image_write.h vec2.h vec3.h
	g++ -std=c++17 -Wall -Wextra -pedantic -O3 -march=native -fopenmp -o FractalTracer main.cpp

clean:
	-rm FractalTracer

.PHONY: clean
